version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www
        environment:
            - APP_ENV=local
            - DB_HOST=db
            - DB_PORT=3306
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel_net
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost" ]
            interval: 30s
            timeout: 10s
            retries: 3

    web:
        image: nginx:1.25-alpine
        container_name: nginx_web
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_net
        restart: unless-stopped

    db:
        image: mysql:8
        container_name: mysql_db
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_net
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 30s
            timeout: 10s
            retries: 5

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: pma
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 100000000
        depends_on:
            - db
        networks:
            - laravel_net

networks:
    laravel_net:

volumes:
    dbdata:
